version: '3.9'

services:
  build-enclave:
    image: nix-sgx-hashmachine
    build:
      context: .
      dockerfile: nix.Dockerfile
    volumes:
      - ./enclave.nix:/usr/src/enclave.nix
      - ./nix:/usr/src/nix
